### ISSUE TITLE
LDAP Script doesn't start

### ISSUE THREAD

**Issue by gianklug** [mumble-voip/mumble-scripts#33]
When I try to start `LDAPauth.py` with ice enabled and the right credentials and port I get the following error in the Logfile:
```
icecpp: error: cannot open `/usr/local/sbin/Murmur.ice' for reading
Traceback (most recent call last):
  File "/usr/local/sbin/LDAPauth.py", line 881, in <module>
    do_main_program()
  File "/usr/local/sbin/LDAPauth.py", line 219, in do_main_program
    Ice.loadSlice('', ["-I/usr/share/slice/","Murmur.ice"])
RuntimeError: Slice preprocessing failed for `'`
```
I already tried forcing another ice path but as you can see in the first line, it somehow tries to find the .ice in the Directory the Script is in.

**Comment by Krzmbrzl** [comment]
what version of Mumble are you using?

> it somehow tries to find the .ice in the Directory the Script is in.

have you tried copying the `Murmur.ice` file from the Mumble source tree (`src/murmur/Murmur.ice`) to the directory in which you are executing the script?

**Comment by gianklug** [comment]
I use version 1.3.4-1, the latest one available in the Debian Bullseye repo.
I will try copying later.

**Comment by gianklug** [comment]
Symlinking the file worked, however I still think this needs some fixing

**Comment by Kissaki** [comment]
https://github.com/mumble-voip/mumble-scripts/blob/master/Authenticators/LDAP/LDAPauth.py#L214-L219

The logic seems to use the python Ice module to get the correct directory path, and otherwise two default include paths. So if the python ice module is installed via package manager I would expect this to work and search in the systems Ice slice dir path.
