### ISSUE TITLE
 LDAPauth.py No module named 'Ice.Py3'

### ISSUE THREAD

**Issue by tjensch** [mumble-voip/mumble-scripts#36]
Running Ubuntu 22.04 I stumbled upon an error when trying to make mumble-server (1.3.4-1ubuntu1) work with my ldap. 
I have installed the suggested packages: zeroc-ice-slice python3-daemon python3-ldap python3-zeroc-ice
```
Dec 23 16:14:57 baldr LDAPauth.py[25811]: Traceback (most recent call last):
Dec 23 16:14:57 baldr LDAPauth.py[25811]:   File "/usr/local/sbin/LDAPauth.py", line 114, in <module>
Dec 23 16:14:57 baldr LDAPauth.py[25811]:     import Ice
Dec 23 16:14:57 baldr LDAPauth.py[25811]:   File "/usr/lib/python3/dist-packages/Ice/__init__.py", line 78, in <module>
Dec 23 16:14:57 baldr LDAPauth.py[25811]:     from Ice.Py3.IceFuture import FutureBase, wrap_future
Dec 23 16:14:57 baldr LDAPauth.py[25811]: ModuleNotFoundError: No module named 'Ice.Py3'

```

**Comment by Krzmbrzl** [comment]
Without knowing anything about this, the error message seems to indicate that the script is importing Ice bindings specifically for Python3. By now this is probably assumed to be the default (or even required), which presumably led to removal of said module.

If I were you I would try to see what happens if you delete that import :thinking:
